import {StyleSheet} from 'react-native';
import {dSize, normalize} from '../../config/typography';

export default StyleSheet.create({
  pray_btn: {
    width: 376,
    height: 115,
    shadowColor: 'rgba(0, 0, 0, 0.4)',
    shadowOffset: {width: 3, height: 0},
    shadowRadius: 6,
    borderRadius: 20,
    borderColor: '#ffffff',
    borderStyle: 'solid',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 7,
  },
  pray_btn_active: {
    width: 376,
    height: 115,
    shadowColor: '#f1ea90',
    shadowOffset: {width: 0, height: 4},
    shadowRadius: 10,
    borderRadius: 20,
    borderColor: '#f5ebd6',
    borderStyle: 'solid',
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 7,
  },
  pray_btn_img: {
    position: 'absolute',
  },
  pray_btn_text: {
    height: 31,
    textShadowColor: 'rgba(0, 0, 0, 0.7)',
    textShadowOffset: {width: 1, height: 2},
    textShadowRadius: 2,
    color: '#ffffff',
    fontFamily: 'Lato-Regular',
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: 1,
    lineHeight: 30,
  },
});
